sudo: require
services:
  - docker

before_install:
  - docker build -t sripathyk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sripathyk/react-test npm test -- --coverage

after_success:
  - docker build -t sripathyk/multi-client ./client
  - docker build -t sripathyk/multi-nginx ./nginx
  - docker build -t sripathyk/multi-server ./server
  - docker build -t sripathyk/multi-worker ./worker
  # Login to Docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker HUB
  - docker push sripathyk/multi-client
  - docker push sripathyk/multi-nginx
  - docker push sripathyk/multi-server
  - docker push sripathyk/multi-worker

# Push project to AWS ElasticBeanStalk
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-790546918280"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_KEY"

